# `env` 下的所有键值对将会被添加为环境变量
env:  
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  opacity: 0.8
  padding:
    x: 2
    y: 2

colors:
  primary:
    background: "#1e2127"
    # background: "#2E3440"
    foreground: "#D8DEE9"

  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#abb2bf"

  bright:
    black: "#5c6370"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#d19a66"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#ECEFF4"


    # 设置字体
font:
  normal:
    family: "Source Code Pro"
    style: Regular
  bold:
    family: "Source Code Pro"
    style: Bold
  italic:
    family: "Source Code Pro"
    style: Italic
  bold_italic:
    family: "Source Code Pro"
    style: Bold Italic

    # 字大小
  size: 12.0 

  # 每个字符的间的字间距。"offset.y" 可以控制行距，"offset.x" 可以改变字符间距。
  offset:
    x: 1
    y: 0
  glyph_offset:
    x: 0
    y: 0

scrolling:
  # 回滚缓冲区中的最大行数,指定“0”将禁用滚动。
  history: 10000

  # 滚动行数 
  multiplier: 10

  # 如果为‘true’，则使用亮色变体绘制粗体文本。
draw_bold_text_with_bright_colors: true

selection:
  # 分割语义化单词的分隔符，这个会影响到鼠标双击左键的单词选中。
  # 比如 @ 作为分割 username 和 password 的字符，默认配置里面竞是没有的。。。
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  # 选中文本后是否复制到主剪贴板 https://wiki.archlinux.org/index.php/clipboard
  save_to_clipboard: true

# 是否启用配置热更新
live_config_reload: true

key_bindings:
  - { key: V, mods: command, action: Paste }
  - { key: C, mods: command, action: Copy }
