theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
#垂直缩进参考线
render = true

[keys.normal]
C-s = ":w"
"C-/" = "toggle_comments"
C-k = "half_page_up"
C-j = "half_page_down"
A-h = "goto_line_start"
A-l = "goto_line_end"
